### ISSUE TITLE
Quarto parameter evaluation in interactive session

### ISSUE THREAD

**Issue by jasonpott** [R-nvim/R.nvim#255]
When working with Quarto documents interactively in Rstudio it is possible to evaluate the parameters set within the Quarto YAML header during code execution.

In Rnvim these parameters are only available on preview of the quarto file. I presume this might be some custom option built into Rstudio so might not be available to Rnvim?

A working example.
In Rstudio the below example in an interactive session will be able to produce the object pc_codes containing the three snomed codes from the YAML params. In Rnvim this functionality is not replicated.

YAML Header

```
format:
  pdf:
    toc: true
    documentclass: report
    margin-left: 20mm
    margin-right: 20mm
    margin-top: 20mm
    margin-bottom: 20mm
params:
  pc_search: true
  pc_1: "267102003"
  pc_2: "421581006"
  pc_3: "40739000"
  start_date: "2023-01-01"
  end_date: "2024-08-31"
  disease: "Sore Throat"
title: "Summary data for `r params$disease` presentations from `r params$start_date` - `r params$end_date`"
author: "Jason Pott"
```
R Chunk
```{r}
pc_codes <- c(
  if(!is.null(params$pc_1)){params$pc_1},
  if(!is.null(params$pc_2)){params$pc_2},
  if(!is.null(params$pc_3)){params$pc_3}
)

```

Obviously very grateful for the time and effort put into Rnvim I use it daily and understand if this feature parity is out of scope.
