### ISSUE TITLE
R.nvim incorrectly parses the YAML header when value: is present

### ISSUE THREAD

**Issue by idavydov** [R-nvim/R.nvim#261]
YAML header of R Markdown and Quarto (?) can include `params` attributes, in which case the actual value is passed using the `value:` attribute. E.g. (from [here](https://bookdown.org/yihui/rmarkdown/params-knit.html)):

```yaml
---
title: My Document
output: html_document
params:
  year:
    label: "Year"
    value: 2017
    input: slider
    min: 2010
    max: 2018
    step: 1
    sep: ""
  region:
    label: "Region:"
    value: Europe
    input: select
    choices: [North America, Europe, Asia, Africa]
  printcode:
    label: "Display Code:"
    value: TRUE
  data:
    label: "Input dataset:"
    value: results.csv
    input: file
---
```

Currently `R.nvim` incorrectly interprets such cases. Minimal reproducible example:

````
---
params:
  a: 2
  b:
    value: 3
---

```{r}
print(params$b)
```
## $value
## [1] 3
````

The correct value can be inferred using `knitr::knit_params()`.

```
> knitr::knit_params(
+ r"(
+ ---
+ params:
+   a: 2
+   b:
+     value: 3
+ ---
+ )"
+ )
$a
$value
[1] 2

$name
[1] "a"

attr(,"class")
[1] "knit_param"

$b
$value
[1] 3

$name
[1] "b"

attr(,"class")
[1] "knit_param"
```
